### ISSUE TITLE
build error @ npm run start

### ISSUE THREAD

**Issue by Laziemo** [BCNetio/BlockStackWallet#2]
hi team

when executing 'npm run start', this error is thrown: 

bcnet.io@1.0.0 prestart /home/amoeba/BlockStackWallet
node node_modules/webpack/bin/webpack.js --config lib.webpack.config.js
/home/amoeba/BlockStackWallet/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/amoeba/BlockStackWallet/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at /home/amoeba/BlockStackWallet/node_modules/webpack-cli/bin/webpack.js:60:27
    at Object.<anonymous> (/home/amoeba/BlockStackWallet/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcnet.io@1.0.0 prestart: `node node_modules/webpack/bin/webpack.js --config lib.webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bcnet.io@1.0.0 prestart script.

**Comment by builat** [comment]
@Laziemo Hello. This error related to webpack DllReferencePlugin. Please tell your npm and nodejs version.

Fast way to fix is to remove initialisation of this plugins from webpack 

https://github.com/BCNetio/BlockStackWallet/blob/035ec86ced0561392f137ec318272ffea523cb6c/webpack.config.js#L81 

and 

https://github.com/BCNetio/BlockStackWallet/blob/035ec86ced0561392f137ec318272ffea523cb6c/package.json#L8 prestart initialisation line.

Right way I probably could advice you after information about node and npm version.

**Comment by Laziemo** [comment]
node v10.9.0
npm v6.2.0

**Comment by builat** [comment]
@Laziemo solution is to update webpack to 3.1.1.
I'll update package.json in few minutes. Tnx for your report!

**Comment by Laziemo** [comment]
Cheers @builat !
